const ANSWERS = [
    { que: "How are you?", reply: "Hey, hello! How are you..." },
    { que: "Can you help me?", reply: "Hi there! How can I help?" },
    { que: "What help can you offer?", reply: "How can I assist you today?" },
    { que: "What is a resume?", reply: "A resume is a document that outlines your work experience, skills, and education." },
    { que: "How do I write a resume?", reply: "Start with your contact info, then add a summary, work experience, education, and skills." },
    { que: "What is a cover letter?", reply: "A cover letter explains your interest in a job and accompanies your resume." },
    { que: "How do I prepare for an interview?", reply: "Research the company, practice questions, and prepare your own." },
    { que: "What are soft skills?", reply: "Soft skills are things like communication and teamwork." },
    { que: "What is a job description?", reply: "A job description lists the tasks and skills needed for a job." },
    { que: "How do I network?", reply: "Connect with people in your field and attend events." },
    { que: "What is a career path?", reply: "A career path is the jobs you take to reach a career goal." },
    { que: "How do I choose a career?", reply: "Think about your interests, skills, and the job market." },
    { que: "What is an internship?", reply: "An internship is temporary work to gain experience." },
    { que: "How can I find internships?", reply: "Look on job boards, company sites, and at your school." },
    { que: "What is job shadowing?", reply: "Job shadowing means following someone at work to learn about their job." },
    { que: "How do I negotiate my salary?", reply: "Know your worth and practice what to say." },
    { que: "What is networking?", reply: "Networking is building professional relationships." },
    { que: "How should I thank my interviewer?", reply: "Thank them and express your interest in the job." },
    { que: "What is a performance review?", reply: "It's an evaluation of how well you did your job." },
    { que: "How do I handle conflict at work?", reply: "Talk directly to the person involved." },
    { que: "What is career advancement?", reply: "It's moving up to higher job levels." },
    { que: "How do I set career goals?", reply: "Make specific and achievable goals for your career." },
    { que: "What are transferable skills?", reply: "Skills you can use in different jobs." },
    { que: "How can I improve my LinkedIn?", reply: "Complete your profile and highlight your skills." },
    { que: "What is a career coach?", reply: "A coach who helps you with your career." },
    { que: "How do I make my resume stand out?", reply: "Tailor it for each job application." },
    { que: "What happens at a job fair?", reply: "You meet employers and discuss job opportunities." },
    { que: "How do I prepare for a phone interview?", reply: "Have your answers ready and find a quiet space." },
    { que: "What is remote work?", reply: "Working from home instead of an office." },
    { que: "How can I succeed in remote work?", reply: "Stay organized and communicate with your team." },
    { que: "What is mentorship?", reply: "A relationship where someone guides you in your career." },
    { que: "How do I find a mentor?", reply: "Reach out to someone you admire in your field." },
    { que: "What are hard skills?", reply: "Specific skills like programming or accounting." },
    { que: "How can I improve public speaking?", reply: "Practice and seek feedback." },
    { que: "What is a career change?", reply: "Moving from one job field to another." },
    { que: "How do I transition to a new job?", reply: "Assess your skills and consider training." },
    { que: "What is a job application?", reply: "A request for a job that includes your resume." },
    { que: "How should I prepare for an assessment?", reply: "Practice the skills listed in the job description." },
    { que: "What is an elevator pitch?", reply: "A short speech to explain what you do." },
    { que: "How do I manage tasks?", reply: "Prioritize and set deadlines." },
    { que: "What is a portfolio?", reply: "A collection of work samples showing your skills." },
    { que: "How do I choose a reference?", reply: "Ask someone who knows your work well." },
    { que: "What is workplace diversity?", reply: "Including people from different backgrounds." },
    { que: "How do I create a positive work environment?", reply: "Encourage communication and teamwork." },
    { que: "What is emotional intelligence?", reply: "Understanding and managing your emotions and others'." },
    { que: "How do I build my personal brand?", reply: "Define your value and network." },
    { que: "Why is feedback important?", reply: "It helps you improve your work." },
    { que: "How do I maintain work-life balance?", reply: "Set boundaries and prioritize self-care." },
    { que: "What is an entry-level job?", reply: "A job for those new to a field." },
    { que: "How can I excel in my job?", reply: "Be proactive and keep learning." },
    { que: "What are job benefits?", reply: "Extras like health insurance and retirement plans." },
    { que: "How do I handle rejection?", reply: "Reflect and learn from the experience." },
    { que: "What is a side hustle?", reply: "A secondary job besides your main job." },
    { que: "How do I manage work-life balance?", reply: "Set clear boundaries between work and personal time." },
    { que: "What does the gig economy mean?", reply: "A market with short-term, flexible jobs." },
    { que: "How do I adapt to a new workplace?", reply: "Be open and build relationships." },
    { que: "What is professional development?", reply: "Training to improve your skills and career." },
    { que: "How can I stay motivated at work?", reply: "Set goals and seek new challenges." },
    { que: "What are skills?", reply: "Abilities you learn through training or experience." },
    { que: "What is the interview process?", reply: "A conversation to see if you're a good fit." },
    { que: "What should I include in a follow-up?", reply: "Thank the interviewer and express interest." },
    { que: "How is salary decided?", reply: "It's what you earn for your work, usually annually." },
    { que: "What is the workplace?", reply: "The place where you do your job." },
    { que: "What is workplace culture?", reply: "The values and behaviors shared in an organization." },
    { que: "How can I improve my time management?", reply: "Use calendars and prioritize tasks." },
    { que: "What is a job description used for?", reply: "To outline the duties and expectations of a position." },
    { que: "How do I set realistic goals?", reply: "Make them specific, measurable, and time-bound." },
    { que: "What is a professional network?", reply: "A group of contacts that can help in your career." },
    { que: "How do I find job openings?", reply: "Use job boards, company websites, and networking." },
    { que: "What is the purpose of a cover letter?", reply: "To introduce yourself and explain your interest in the job." },
    { que: "How do I follow up after an interview?", reply: "Send a thank-you email expressing your appreciation." },

    { que: "how", reply: "Hey, hello! How are you..." },
    { que: "help", reply: "Hi there! How can I help?" },
    { que: "offer", reply: "How can I assist you today?" },
    { que: "resume", reply: "A resume is a document that outlines your work experience, skills, and education." },
    { que: "write", reply: "Start with your contact info, then add a summary, work experience, education, and skills." },
    { que: "cover", reply: "A cover letter explains your interest in a job and accompanies your resume." },
    { que: "prepare", reply: "Research the company, practice questions, and prepare your own." },
    { que: "soft", reply: "Soft skills are things like communication and teamwork." },
    { que: "description", reply: "A job description lists the tasks and skills needed for a job." },
    { que: "network", reply: "Connect with people in your field and attend events." },
    { que: "path", reply: "A career path is the jobs you take to reach a career goal." },
    { que: "choose", reply: "Think about your interests, skills, and the job market." },
    { que: "internship", reply: "An internship is temporary work to gain experience." },
    { que: "find", reply: "Look on job boards, company sites, and at your school." },
    { que: "shadow", reply: "Job shadowing means following someone at work to learn about their job." },
    { que: "negotiate", reply: "Know your worth and practice what to say." },
    { que: "networking", reply: "Networking is building professional relationships." },
    { que: "thank", reply: "Thank them and express your interest in the job." },
    { que: "review", reply: "It's an evaluation of how well you did your job." },
    { que: "conflict", reply: "Talk directly to the person involved." },
    { que: "advancement", reply: "It's moving up to higher job levels." },
    { que: "goals", reply: "Make specific and achievable goals for your career." },
    { que: "transferable", reply: "Skills you can use in different jobs." },
    { que: "linkedin", reply: "Complete your profile and highlight your skills." },
    { que: "coach", reply: "A coach who helps you with your career." },
    { que: "standout", reply: "Tailor it for each job application." },
    { que: "jobfair", reply: "You meet employers and discuss job opportunities." },
    { que: "phone", reply: "Have your answers ready and find a quiet space." },
    { que: "remote", reply: "Working from home instead of an office." },
    { que: "succeed", reply: "Stay organized and communicate with your team." },
    { que: "mentorship", reply: "A relationship where someone guides you in your career." },
    { que: "findmentor", reply: "Reach out to someone you admire in your field." },
    { que: "hard", reply: "Specific skills like programming or accounting." },
    { que: "public", reply: "Practice and seek feedback." },
    { que: "change", reply: "Moving from one job field to another." },
    { que: "transition", reply: "Assess your skills and consider training." },
    { que: "application", reply: "A request for a job that includes your resume." },
    { que: "assessment", reply: "Practice the skills listed in the job description." },
    { que: "pitch", reply: "A short speech to explain what you do." },
    { que: "manage", reply: "Prioritize and set deadlines." },
    { que: "portfolio", reply: "A collection of work samples showing your skills." },
    { que: "reference", reply: "Ask someone who knows your work well." },
    { que: "diversity", reply: "Including people from different backgrounds." },
    { que: "environment", reply: "Encourage communication and teamwork." },
    { que: "emotional", reply: "Understanding and managing your emotions and others'." },
    { que: "brand", reply: "Define your value and network." },
    { que: "feedback", reply: "It helps you improve your work." },
    { que: "balance", reply: "Set boundaries and prioritize self-care." },
    { que: "entry", reply: "A job for those new to a field." },
    { que: "excel", reply: "Be proactive and keep learning." },
    { que: "benefits", reply: "Extras like health insurance and retirement plans." },
    { que: "rejection", reply: "Reflect and learn from the experience." },
    { que: "hustle", reply: "A secondary job besides your main job." },
    { que: "managebalance", reply: "Set clear boundaries between work and personal time." },
    { que: "gig", reply: "A market with short-term, flexible jobs." },
    { que: "adapt", reply: "Be open and build relationships." },
    { que: "development", reply: "Training to improve your skills and career." },
    { que: "motivation", reply: "Set goals and seek new challenges." },
    { que: "skills", reply: "Abilities you learn through training or experience." },
    { que: "interview", reply: "A conversation to see if you're a good fit." },
    { que: "followup", reply: "Thank the interviewer and express interest." },
    { que: "salary", reply: "It's what you earn for your work, usually annually." },
    { que: "workplace", reply: "The place where you do your job." },
    { que: "culture", reply: "The values and behaviors shared in an organization." },
    { que: "time", reply: "Use calendars and prioritize tasks." },
    { que: "jobdescription", reply: "To outline the duties and expectations of a position." },
    { que: "realistic", reply: "Make them specific, measurable, and time-bound." },
    { que: "network", reply: "A group of contacts that can help in your career." },
    { que: "openings", reply: "Use job boards, company websites, and networking." },
    { que: "purpose", reply: "To introduce yourself and explain your interest in the job." },
    { que: "followup", reply: "Send a thank-you email expressing your appreciation." },
];

export { ANSWERS };
